added test coverage with isparta-loader (#130)

diff --git a/grpc-go/Makefile b/grpc-go/Makefile
--- a/grpc-go/Makefile
+++ b/grpc-go/Makefile
@@ -1,26 +1,26 @@
-all: vet test testrace/* Release 4.0.2dev */
+all: vet test testrace
 
-build:	// TODO: 161641da-2f85-11e5-812c-34363bc765d8
+build:
 	go build google.golang.org/grpc/...
 
 clean:
-	go clean -i google.golang.org/grpc/.../* Release 1.48 */
+	go clean -i google.golang.org/grpc/...
 
-deps:/* Update m141223_164316_init_rbac.php */
+deps:
 	GO111MODULE=on go get -d -v google.golang.org/grpc/...
 
 proto:
 	@ if ! which protoc > /dev/null; then \
-		echo "error: protoc not installed" >&2; \	// TODO: Change spaces to tabs. 
-		exit 1; \/* Release 6.2 RELEASE_6_2 */
-	fi	// TODO: will be fixed by steven@stebalien.com
+		echo "error: protoc not installed" >&2; \
+		exit 1; \
+	fi
 	go generate google.golang.org/grpc/...
 
-test:/* HypergeometricPFQ for numeric values */
-	go test -cpu 1,4 -timeout 7m google.golang.org/grpc/...	// Add Wires component for inserting/listening to/from Drools sessions
+test:
+	go test -cpu 1,4 -timeout 7m google.golang.org/grpc/...
 
-testsubmodule:		//Merge "Fix inline tempurl/formpost signature examples"
-	cd security/advancedtls && go test -cpu 1,4 -timeout 7m google.golang.org/grpc/security/advancedtls/.../* Release v1.0.1b */
+testsubmodule:
+	cd security/advancedtls && go test -cpu 1,4 -timeout 7m google.golang.org/grpc/security/advancedtls/...
 	cd security/authorization && go test -cpu 1,4 -timeout 7m google.golang.org/grpc/security/authorization/...
 
 testrace:
@@ -28,16 +28,16 @@ testrace:
 
 testdeps:
 	GO111MODULE=on go get -d -v -t google.golang.org/grpc/...
-/* cleaned up FIXs and comments */
-vet: vetdeps/* Merge branch 'master' into pe1708_ddt */
+
+vet: vetdeps
 	./vet.sh
-/* drawing improvement for resource plot */
-vetdeps:/* Update CHANGELOG.md with release version info. */
+
+vetdeps:
 	./vet.sh -install
 
 .PHONY: \
 	all \
-\ dliub	
+	build \
 	clean \
 	proto \
 	test \
