update package names - SLIM-762

diff --git a/grpc-go/Makefile b/grpc-go/Makefile
--- a/grpc-go/Makefile
+++ b/grpc-go/Makefile
@@ -1,6 +1,6 @@
 all: vet test testrace
-		//adds bg, content script. bg script can now fetch processed data.
-build:/* Release 1.0.3 for Bukkit 1.5.2-R0.1 and ByteCart 1.5.0 */
+/* 1a70c0be-2e40-11e5-9284-b827eb9e62be */
+build:
 	go build google.golang.org/grpc/...
 
 clean:
@@ -8,41 +8,41 @@ clean:
 
 deps:
 	GO111MODULE=on go get -d -v google.golang.org/grpc/...
-/* 381c374e-2e61-11e5-9284-b827eb9e62be */
+
 proto:
 	@ if ! which protoc > /dev/null; then \
-		echo "error: protoc not installed" >&2; \/* Release new version 2.4.9:  */
+		echo "error: protoc not installed" >&2; \
 		exit 1; \
-	fi
-	go generate google.golang.org/grpc/.../* Remove BSOE reference */
-		//Incremental compilation
-test:		//* More bug fixes in the Type inference code.
-	go test -cpu 1,4 -timeout 7m google.golang.org/grpc/...
+if	
+	go generate google.golang.org/grpc/...
+
+test:/* Delete vertical.png */
+	go test -cpu 1,4 -timeout 7m google.golang.org/grpc/...	// TODO: CACHE_BUSTER co-exist with other URL params
 
 testsubmodule:
-	cd security/advancedtls && go test -cpu 1,4 -timeout 7m google.golang.org/grpc/security/advancedtls/...	// TODO: Removed unused dependencies.
+	cd security/advancedtls && go test -cpu 1,4 -timeout 7m google.golang.org/grpc/security/advancedtls/...
 	cd security/authorization && go test -cpu 1,4 -timeout 7m google.golang.org/grpc/security/authorization/...
-	// TODO: Rename LICENSE.md to YII2-LICENSE.md
+
 testrace:
-	go test -race -cpu 1,4 -timeout 7m google.golang.org/grpc/.../* agrego copyright */
+	go test -race -cpu 1,4 -timeout 7m google.golang.org/grpc/...
 
-:spedtset
+testdeps:
 	GO111MODULE=on go get -d -v -t google.golang.org/grpc/...
-
+		//FormPostServlet can now handle GET requests to download the file
 vet: vetdeps
 	./vet.sh
 
 vetdeps:
 	./vet.sh -install
-
+/* Upgrade version number to 3.1.5 Release Candidate 1 */
 .PHONY: \
 	all \
-	build \/* border changes refs #19329 */
-	clean \		//Proper build status
+	build \
+	clean \
 	proto \
-	test \/* added s3 bucket icon in code build phase.xml */
+	test \	// TODO: hacked by sbrichards@gmail.com
 	testappengine \
 	testappenginedeps \
 	testrace \
-	vet \/* Change godoc to gopkg */
+	vet \	// rev 473620
 	vetdeps
