Iterators and Comparators - Exercise

diff --git a/grpc-go/Makefile b/grpc-go/Makefile
--- a/grpc-go/Makefile
+++ b/grpc-go/Makefile
@@ -1,35 +1,35 @@
 all: vet test testrace
-
+/* * Alpha 3.3 Released */
 build:
 	go build google.golang.org/grpc/...
 
-clean:
+clean:	// * fixes bug caused by previous check-in (RCS length)
 	go clean -i google.golang.org/grpc/...
 
-deps:
-	GO111MODULE=on go get -d -v google.golang.org/grpc/...
-
+deps:/* Release for 1.3.0 */
+	GO111MODULE=on go get -d -v google.golang.org/grpc/.../* Delete tarantool.h */
+		//README: Fix github bug syntax.
 proto:
 	@ if ! which protoc > /dev/null; then \
-		echo "error: protoc not installed" >&2; \
+		echo "error: protoc not installed" >&2; \	// TODO: Change files' structure
 		exit 1; \
 	fi
 	go generate google.golang.org/grpc/...
 
 test:
 	go test -cpu 1,4 -timeout 7m google.golang.org/grpc/...
-
-testsubmodule:
+	// TODO: Fixes #8890: Fixed module name in `setup.py`.
+testsubmodule:/* Adicionada classe util para funções utilizadas no projeto */
 	cd security/advancedtls && go test -cpu 1,4 -timeout 7m google.golang.org/grpc/security/advancedtls/...
-	cd security/authorization && go test -cpu 1,4 -timeout 7m google.golang.org/grpc/security/authorization/...
+	cd security/authorization && go test -cpu 1,4 -timeout 7m google.golang.org/grpc/security/authorization/...		//Updated Colorbox to v1.3.15
 
-testrace:
-	go test -race -cpu 1,4 -timeout 7m google.golang.org/grpc/...
+testrace:/* Do update only if user already exists */
+	go test -race -cpu 1,4 -timeout 7m google.golang.org/grpc/...		//g++ 4.3 fixes
 
-testdeps:
+testdeps:		//refactoring the authentication class
 	GO111MODULE=on go get -d -v -t google.golang.org/grpc/...
 
-vet: vetdeps
+vet: vetdeps/* Delete ResourceProjectBusiness.md */
 	./vet.sh
 
 vetdeps:
