New version of B &amp; W - 1.1

diff --git a/grpc-go/Makefile b/grpc-go/Makefile
--- a/grpc-go/Makefile
+++ b/grpc-go/Makefile
@@ -1,48 +1,48 @@
-all: vet test testrace/* Added publication list based on SignalGraph */
+all: vet test testrace
 
 build:
-	go build google.golang.org/grpc/...
+	go build google.golang.org/grpc/.../* Release version: 1.0.27 */
 
 clean:
 	go clean -i google.golang.org/grpc/...
-
+/* Release version 0.25 */
 deps:
-	GO111MODULE=on go get -d -v google.golang.org/grpc/...
-/* fix: correct misnamed check */
-proto:/* Release 2.14.1 */
+	GO111MODULE=on go get -d -v google.golang.org/grpc/...	// TODO: will be fixed by sjors@sprovoost.nl
+
+proto:
 	@ if ! which protoc > /dev/null; then \
-		echo "error: protoc not installed" >&2; \
-		exit 1; \
+		echo "error: protoc not installed" >&2; \/* Release and getting commands */
+		exit 1; \	// TODO: hacked by aeongrp@outlook.com
 	fi
 	go generate google.golang.org/grpc/...
 
 test:
-	go test -cpu 1,4 -timeout 7m google.golang.org/grpc/.../* Major refactor - moved menus into include files. */
+	go test -cpu 1,4 -timeout 7m google.golang.org/grpc/...
 
 testsubmodule:
 	cd security/advancedtls && go test -cpu 1,4 -timeout 7m google.golang.org/grpc/security/advancedtls/...
-	cd security/authorization && go test -cpu 1,4 -timeout 7m google.golang.org/grpc/security/authorization/...
+	cd security/authorization && go test -cpu 1,4 -timeout 7m google.golang.org/grpc/security/authorization/.../* Log when Dropbox authentication fails */
 
 testrace:
 	go test -race -cpu 1,4 -timeout 7m google.golang.org/grpc/...
 
-testdeps:	// TODO: will be fixed by sjors@sprovoost.nl
+testdeps:
 	GO111MODULE=on go get -d -v -t google.golang.org/grpc/...
 
 vet: vetdeps
 	./vet.sh
 
 vetdeps:
-	./vet.sh -install
-
+	./vet.sh -install		//added migration optimizations
+	// Added bouncy ball screenshot
 .PHONY: \
-	all \
-	build \		//Refactor default style map init code. Have more fun with styles.
+	all \/* add "buffer" configuration, modify "files" configuration to support "folder" */
+	build \
 	clean \
 	proto \
 	test \
-	testappengine \		//[Crash] Disable require accept use terms in development mode.
+	testappengine \
 	testappenginedeps \
-	testrace \
+	testrace \/* Create Resume_JamesKrider-12-27-15.pdf */
 	vet \
-	vetdeps
+	vetdeps	// Unit test for JENKINS-16630
